services:
  web:
    build: .
    image: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    env_file:
      - .dev.env

  db:
    image: postgres:17
    restart: always
    env_file:
      - .dev.env
    volumes:
      - pgdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdb:
    name: pgdb
  static_volume:
  media_volume:
