services:
  web:
    build: .
    image: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:8000"
    depends_on:
      - db
    restart: always
    env_file:
      - .dev.env

  db:
    image: postgres:15
    restart: always
    env_file:
      - .dev.env
    volumes:
      - pgdb:/var/lib/postgresql/data
      - ./backup:/backup
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A teacher_portal worker -l info --pool=solo
    volumes:
      - .:/app
    env_file:
      - .dev.env
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    command: celery -A teacher_portal beat -l info
    volumes:
      - .:/app
    env_file:
      - .dev.env
    depends_on:
      - redis
      - db

volumes:
  pgdb:
    name: pgdb
  static_volume:
  media_volume:
