# Generated by Django 5.1.2 on 2025-08-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Teacher'), (2, 'Student'), (3, 'Admin')], default=1),
        ),
    ]
